/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecoverPassVerifyCodeRouteImport } from './routes/recover-pass/verify-code'
import { Route as RecoverPassResetRouteImport } from './routes/recover-pass/reset'
import { Route as RecoverPassCheckEmailRouteImport } from './routes/recover-pass/check-email'
import { Route as authorizedAuthorizedLayoutRouteImport } from './routes/(authorized)/_authorized-layout'
import { Route as authorizedAuthorizedLayoutHouseRouteImport } from './routes/(authorized)/_authorized-layout/house'
import { Route as authorizedAuthorizedLayoutHomeRouteImport } from './routes/(authorized)/_authorized-layout/home'
import { Route as authorizedAuthorizedLayoutApartmentRouteImport } from './routes/(authorized)/_authorized-layout/apartment'
import { Route as authorizedAuthorizedLayoutbookingsBookingNewRouteImport } from './routes/(authorized)/_authorized-layout/(bookings)/booking-new'
import { Route as authorizedAuthorizedLayoutbookingsBookingListRouteImport } from './routes/(authorized)/_authorized-layout/(bookings)/booking-list'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPassVerifyCodeRoute = RecoverPassVerifyCodeRouteImport.update({
  id: '/recover-pass/verify-code',
  path: '/recover-pass/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPassResetRoute = RecoverPassResetRouteImport.update({
  id: '/recover-pass/reset',
  path: '/recover-pass/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPassCheckEmailRoute = RecoverPassCheckEmailRouteImport.update({
  id: '/recover-pass/check-email',
  path: '/recover-pass/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authorizedAuthorizedLayoutRoute =
  authorizedAuthorizedLayoutRouteImport.update({
    id: '/(authorized)/_authorized-layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const authorizedAuthorizedLayoutHouseRoute =
  authorizedAuthorizedLayoutHouseRouteImport.update({
    id: '/house',
    path: '/house',
    getParentRoute: () => authorizedAuthorizedLayoutRoute,
  } as any)
const authorizedAuthorizedLayoutHomeRoute =
  authorizedAuthorizedLayoutHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => authorizedAuthorizedLayoutRoute,
  } as any)
const authorizedAuthorizedLayoutApartmentRoute =
  authorizedAuthorizedLayoutApartmentRouteImport.update({
    id: '/apartment',
    path: '/apartment',
    getParentRoute: () => authorizedAuthorizedLayoutRoute,
  } as any)
const authorizedAuthorizedLayoutbookingsBookingNewRoute =
  authorizedAuthorizedLayoutbookingsBookingNewRouteImport.update({
    id: '/(bookings)/booking-new',
    path: '/booking-new',
    getParentRoute: () => authorizedAuthorizedLayoutRoute,
  } as any)
const authorizedAuthorizedLayoutbookingsBookingListRoute =
  authorizedAuthorizedLayoutbookingsBookingListRouteImport.update({
    id: '/(bookings)/booking-list',
    path: '/booking-list',
    getParentRoute: () => authorizedAuthorizedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-pass/check-email': typeof RecoverPassCheckEmailRoute
  '/recover-pass/reset': typeof RecoverPassResetRoute
  '/recover-pass/verify-code': typeof RecoverPassVerifyCodeRoute
  '/apartment': typeof authorizedAuthorizedLayoutApartmentRoute
  '/home': typeof authorizedAuthorizedLayoutHomeRoute
  '/house': typeof authorizedAuthorizedLayoutHouseRoute
  '/booking-list': typeof authorizedAuthorizedLayoutbookingsBookingListRoute
  '/booking-new': typeof authorizedAuthorizedLayoutbookingsBookingNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-pass/check-email': typeof RecoverPassCheckEmailRoute
  '/recover-pass/reset': typeof RecoverPassResetRoute
  '/recover-pass/verify-code': typeof RecoverPassVerifyCodeRoute
  '/apartment': typeof authorizedAuthorizedLayoutApartmentRoute
  '/home': typeof authorizedAuthorizedLayoutHomeRoute
  '/house': typeof authorizedAuthorizedLayoutHouseRoute
  '/booking-list': typeof authorizedAuthorizedLayoutbookingsBookingListRoute
  '/booking-new': typeof authorizedAuthorizedLayoutbookingsBookingNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(authorized)/_authorized-layout': typeof authorizedAuthorizedLayoutRouteWithChildren
  '/recover-pass/check-email': typeof RecoverPassCheckEmailRoute
  '/recover-pass/reset': typeof RecoverPassResetRoute
  '/recover-pass/verify-code': typeof RecoverPassVerifyCodeRoute
  '/(authorized)/_authorized-layout/apartment': typeof authorizedAuthorizedLayoutApartmentRoute
  '/(authorized)/_authorized-layout/home': typeof authorizedAuthorizedLayoutHomeRoute
  '/(authorized)/_authorized-layout/house': typeof authorizedAuthorizedLayoutHouseRoute
  '/(authorized)/_authorized-layout/(bookings)/booking-list': typeof authorizedAuthorizedLayoutbookingsBookingListRoute
  '/(authorized)/_authorized-layout/(bookings)/booking-new': typeof authorizedAuthorizedLayoutbookingsBookingNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-pass/check-email'
    | '/recover-pass/reset'
    | '/recover-pass/verify-code'
    | '/apartment'
    | '/home'
    | '/house'
    | '/booking-list'
    | '/booking-new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-pass/check-email'
    | '/recover-pass/reset'
    | '/recover-pass/verify-code'
    | '/apartment'
    | '/home'
    | '/house'
    | '/booking-list'
    | '/booking-new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(authorized)/_authorized-layout'
    | '/recover-pass/check-email'
    | '/recover-pass/reset'
    | '/recover-pass/verify-code'
    | '/(authorized)/_authorized-layout/apartment'
    | '/(authorized)/_authorized-layout/home'
    | '/(authorized)/_authorized-layout/house'
    | '/(authorized)/_authorized-layout/(bookings)/booking-list'
    | '/(authorized)/_authorized-layout/(bookings)/booking-new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  authorizedAuthorizedLayoutRoute: typeof authorizedAuthorizedLayoutRouteWithChildren
  RecoverPassCheckEmailRoute: typeof RecoverPassCheckEmailRoute
  RecoverPassResetRoute: typeof RecoverPassResetRoute
  RecoverPassVerifyCodeRoute: typeof RecoverPassVerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-pass/verify-code': {
      id: '/recover-pass/verify-code'
      path: '/recover-pass/verify-code'
      fullPath: '/recover-pass/verify-code'
      preLoaderRoute: typeof RecoverPassVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-pass/reset': {
      id: '/recover-pass/reset'
      path: '/recover-pass/reset'
      fullPath: '/recover-pass/reset'
      preLoaderRoute: typeof RecoverPassResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-pass/check-email': {
      id: '/recover-pass/check-email'
      path: '/recover-pass/check-email'
      fullPath: '/recover-pass/check-email'
      preLoaderRoute: typeof RecoverPassCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authorized)/_authorized-layout': {
      id: '/(authorized)/_authorized-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedAuthorizedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authorized)/_authorized-layout/house': {
      id: '/(authorized)/_authorized-layout/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof authorizedAuthorizedLayoutHouseRouteImport
      parentRoute: typeof authorizedAuthorizedLayoutRoute
    }
    '/(authorized)/_authorized-layout/home': {
      id: '/(authorized)/_authorized-layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof authorizedAuthorizedLayoutHomeRouteImport
      parentRoute: typeof authorizedAuthorizedLayoutRoute
    }
    '/(authorized)/_authorized-layout/apartment': {
      id: '/(authorized)/_authorized-layout/apartment'
      path: '/apartment'
      fullPath: '/apartment'
      preLoaderRoute: typeof authorizedAuthorizedLayoutApartmentRouteImport
      parentRoute: typeof authorizedAuthorizedLayoutRoute
    }
    '/(authorized)/_authorized-layout/(bookings)/booking-new': {
      id: '/(authorized)/_authorized-layout/(bookings)/booking-new'
      path: '/booking-new'
      fullPath: '/booking-new'
      preLoaderRoute: typeof authorizedAuthorizedLayoutbookingsBookingNewRouteImport
      parentRoute: typeof authorizedAuthorizedLayoutRoute
    }
    '/(authorized)/_authorized-layout/(bookings)/booking-list': {
      id: '/(authorized)/_authorized-layout/(bookings)/booking-list'
      path: '/booking-list'
      fullPath: '/booking-list'
      preLoaderRoute: typeof authorizedAuthorizedLayoutbookingsBookingListRouteImport
      parentRoute: typeof authorizedAuthorizedLayoutRoute
    }
  }
}

interface authorizedAuthorizedLayoutRouteChildren {
  authorizedAuthorizedLayoutApartmentRoute: typeof authorizedAuthorizedLayoutApartmentRoute
  authorizedAuthorizedLayoutHomeRoute: typeof authorizedAuthorizedLayoutHomeRoute
  authorizedAuthorizedLayoutHouseRoute: typeof authorizedAuthorizedLayoutHouseRoute
  authorizedAuthorizedLayoutbookingsBookingListRoute: typeof authorizedAuthorizedLayoutbookingsBookingListRoute
  authorizedAuthorizedLayoutbookingsBookingNewRoute: typeof authorizedAuthorizedLayoutbookingsBookingNewRoute
}

const authorizedAuthorizedLayoutRouteChildren: authorizedAuthorizedLayoutRouteChildren =
  {
    authorizedAuthorizedLayoutApartmentRoute:
      authorizedAuthorizedLayoutApartmentRoute,
    authorizedAuthorizedLayoutHomeRoute: authorizedAuthorizedLayoutHomeRoute,
    authorizedAuthorizedLayoutHouseRoute: authorizedAuthorizedLayoutHouseRoute,
    authorizedAuthorizedLayoutbookingsBookingListRoute:
      authorizedAuthorizedLayoutbookingsBookingListRoute,
    authorizedAuthorizedLayoutbookingsBookingNewRoute:
      authorizedAuthorizedLayoutbookingsBookingNewRoute,
  }

const authorizedAuthorizedLayoutRouteWithChildren =
  authorizedAuthorizedLayoutRoute._addFileChildren(
    authorizedAuthorizedLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  authorizedAuthorizedLayoutRoute: authorizedAuthorizedLayoutRouteWithChildren,
  RecoverPassCheckEmailRoute: RecoverPassCheckEmailRoute,
  RecoverPassResetRoute: RecoverPassResetRoute,
  RecoverPassVerifyCodeRoute: RecoverPassVerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
