/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyCodeRouteImport } from './routes/verify-code'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationRouteImport } from './routes/location'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BookingNewRouteImport } from './routes/booking-new'
import { Route as BookingListRouteImport } from './routes/booking-list'
import { Route as IndexRouteImport } from './routes/index'

const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify-code',
  path: '/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingNewRoute = BookingNewRouteImport.update({
  id: '/booking-new',
  path: '/booking-new',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingListRoute = BookingListRouteImport.update({
  id: '/booking-list',
  path: '/booking-list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-list': typeof BookingListRoute
  '/booking-new': typeof BookingNewRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-code': typeof VerifyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-list': typeof BookingListRoute
  '/booking-new': typeof BookingNewRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-code': typeof VerifyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-list': typeof BookingListRoute
  '/booking-new': typeof BookingNewRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-code': typeof VerifyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-list'
    | '/booking-new'
    | '/forgot-password'
    | '/location'
    | '/login'
    | '/reset-password'
    | '/verify-code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-list'
    | '/booking-new'
    | '/forgot-password'
    | '/location'
    | '/login'
    | '/reset-password'
    | '/verify-code'
  id:
    | '__root__'
    | '/'
    | '/booking-list'
    | '/booking-new'
    | '/forgot-password'
    | '/location'
    | '/login'
    | '/reset-password'
    | '/verify-code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingListRoute: typeof BookingListRoute
  BookingNewRoute: typeof BookingNewRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-code': {
      id: '/verify-code'
      path: '/verify-code'
      fullPath: '/verify-code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-new': {
      id: '/booking-new'
      path: '/booking-new'
      fullPath: '/booking-new'
      preLoaderRoute: typeof BookingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-list': {
      id: '/booking-list'
      path: '/booking-list'
      fullPath: '/booking-list'
      preLoaderRoute: typeof BookingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingListRoute: BookingListRoute,
  BookingNewRoute: BookingNewRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
