/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocationRouteImport } from './routes/location'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as bookingsBookingNewRouteImport } from './routes/(bookings)/booking-new'
import { Route as bookingsBookingListRouteImport } from './routes/(bookings)/booking-list'
import { Route as authAuthLayoutRouteImport } from './routes/(auth)/_authLayout'
import { Route as authAuthLayoutVerifyCodeRouteImport } from './routes/(auth)/_authLayout/verify-code'
import { Route as authAuthLayoutResetPasswordRouteImport } from './routes/(auth)/_authLayout/reset-password'
import { Route as authAuthLayoutLoginRouteImport } from './routes/(auth)/_authLayout/login'
import { Route as authAuthLayoutForgotPasswordRouteImport } from './routes/(auth)/_authLayout/forgot-password'

const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const bookingsBookingNewRoute = bookingsBookingNewRouteImport.update({
  id: '/(bookings)/booking-new',
  path: '/booking-new',
  getParentRoute: () => rootRouteImport,
} as any)
const bookingsBookingListRoute = bookingsBookingListRouteImport.update({
  id: '/(bookings)/booking-list',
  path: '/booking-list',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLayoutRoute = authAuthLayoutRouteImport.update({
  id: '/(auth)/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLayoutVerifyCodeRoute =
  authAuthLayoutVerifyCodeRouteImport.update({
    id: '/verify-code',
    path: '/verify-code',
    getParentRoute: () => authAuthLayoutRoute,
  } as any)
const authAuthLayoutResetPasswordRoute =
  authAuthLayoutResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => authAuthLayoutRoute,
  } as any)
const authAuthLayoutLoginRoute = authAuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthLayoutRoute,
} as any)
const authAuthLayoutForgotPasswordRoute =
  authAuthLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authAuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/location': typeof LocationRoute
  '/booking-list': typeof bookingsBookingListRoute
  '/booking-new': typeof bookingsBookingNewRoute
  '/forgot-password': typeof authAuthLayoutForgotPasswordRoute
  '/login': typeof authAuthLayoutLoginRoute
  '/reset-password': typeof authAuthLayoutResetPasswordRoute
  '/verify-code': typeof authAuthLayoutVerifyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/location': typeof LocationRoute
  '/booking-list': typeof bookingsBookingListRoute
  '/booking-new': typeof bookingsBookingNewRoute
  '/forgot-password': typeof authAuthLayoutForgotPasswordRoute
  '/login': typeof authAuthLayoutLoginRoute
  '/reset-password': typeof authAuthLayoutResetPasswordRoute
  '/verify-code': typeof authAuthLayoutVerifyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/location': typeof LocationRoute
  '/(auth)/_authLayout': typeof authAuthLayoutRouteWithChildren
  '/(bookings)/booking-list': typeof bookingsBookingListRoute
  '/(bookings)/booking-new': typeof bookingsBookingNewRoute
  '/(auth)/_authLayout/forgot-password': typeof authAuthLayoutForgotPasswordRoute
  '/(auth)/_authLayout/login': typeof authAuthLayoutLoginRoute
  '/(auth)/_authLayout/reset-password': typeof authAuthLayoutResetPasswordRoute
  '/(auth)/_authLayout/verify-code': typeof authAuthLayoutVerifyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/location'
    | '/booking-list'
    | '/booking-new'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/location'
    | '/booking-list'
    | '/booking-new'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-code'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/location'
    | '/(auth)/_authLayout'
    | '/(bookings)/booking-list'
    | '/(bookings)/booking-new'
    | '/(auth)/_authLayout/forgot-password'
    | '/(auth)/_authLayout/login'
    | '/(auth)/_authLayout/reset-password'
    | '/(auth)/_authLayout/verify-code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LocationRoute: typeof LocationRoute
  authAuthLayoutRoute: typeof authAuthLayoutRouteWithChildren
  bookingsBookingListRoute: typeof bookingsBookingListRoute
  bookingsBookingNewRoute: typeof bookingsBookingNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(bookings)/booking-new': {
      id: '/(bookings)/booking-new'
      path: '/booking-new'
      fullPath: '/booking-new'
      preLoaderRoute: typeof bookingsBookingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(bookings)/booking-list': {
      id: '/(bookings)/booking-list'
      path: '/booking-list'
      fullPath: '/booking-list'
      preLoaderRoute: typeof bookingsBookingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_authLayout': {
      id: '/(auth)/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_authLayout/verify-code': {
      id: '/(auth)/_authLayout/verify-code'
      path: '/verify-code'
      fullPath: '/verify-code'
      preLoaderRoute: typeof authAuthLayoutVerifyCodeRouteImport
      parentRoute: typeof authAuthLayoutRoute
    }
    '/(auth)/_authLayout/reset-password': {
      id: '/(auth)/_authLayout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authAuthLayoutResetPasswordRouteImport
      parentRoute: typeof authAuthLayoutRoute
    }
    '/(auth)/_authLayout/login': {
      id: '/(auth)/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLayoutLoginRouteImport
      parentRoute: typeof authAuthLayoutRoute
    }
    '/(auth)/_authLayout/forgot-password': {
      id: '/(auth)/_authLayout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authAuthLayoutForgotPasswordRouteImport
      parentRoute: typeof authAuthLayoutRoute
    }
  }
}

interface authAuthLayoutRouteChildren {
  authAuthLayoutForgotPasswordRoute: typeof authAuthLayoutForgotPasswordRoute
  authAuthLayoutLoginRoute: typeof authAuthLayoutLoginRoute
  authAuthLayoutResetPasswordRoute: typeof authAuthLayoutResetPasswordRoute
  authAuthLayoutVerifyCodeRoute: typeof authAuthLayoutVerifyCodeRoute
}

const authAuthLayoutRouteChildren: authAuthLayoutRouteChildren = {
  authAuthLayoutForgotPasswordRoute: authAuthLayoutForgotPasswordRoute,
  authAuthLayoutLoginRoute: authAuthLayoutLoginRoute,
  authAuthLayoutResetPasswordRoute: authAuthLayoutResetPasswordRoute,
  authAuthLayoutVerifyCodeRoute: authAuthLayoutVerifyCodeRoute,
}

const authAuthLayoutRouteWithChildren = authAuthLayoutRoute._addFileChildren(
  authAuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LocationRoute: LocationRoute,
  authAuthLayoutRoute: authAuthLayoutRouteWithChildren,
  bookingsBookingListRoute: bookingsBookingListRoute,
  bookingsBookingNewRoute: bookingsBookingNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
